// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// simple_swap_n
List simple_swap_n(SEXP Re_from, SEXP Re_to, int n, double swap_p, double seed);
RcppExport SEXP _RMatrixSampling_simple_swap_n(SEXP Re_fromSEXP, SEXP Re_toSEXP, SEXP nSEXP, SEXP swap_pSEXP, SEXP seedSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type Re_from(Re_fromSEXP);
    Rcpp::traits::input_parameter< SEXP >::type Re_to(Re_toSEXP);
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< double >::type swap_p(swap_pSEXP);
    Rcpp::traits::input_parameter< double >::type seed(seedSEXP);
    rcpp_result_gen = Rcpp::wrap(simple_swap_n(Re_from, Re_to, n, swap_p, seed));
    return rcpp_result_gen;
END_RCPP
}
// swap_n
List swap_n(SEXP Re_from, SEXP Re_to, int n, SEXP Rw, SEXP Rz_from, SEXP Rz_to, double seed);
RcppExport SEXP _RMatrixSampling_swap_n(SEXP Re_fromSEXP, SEXP Re_toSEXP, SEXP nSEXP, SEXP RwSEXP, SEXP Rz_fromSEXP, SEXP Rz_toSEXP, SEXP seedSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type Re_from(Re_fromSEXP);
    Rcpp::traits::input_parameter< SEXP >::type Re_to(Re_toSEXP);
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< SEXP >::type Rw(RwSEXP);
    Rcpp::traits::input_parameter< SEXP >::type Rz_from(Rz_fromSEXP);
    Rcpp::traits::input_parameter< SEXP >::type Rz_to(Rz_toSEXP);
    Rcpp::traits::input_parameter< double >::type seed(seedSEXP);
    rcpp_result_gen = Rcpp::wrap(swap_n(Re_from, Re_to, n, Rw, Rz_from, Rz_to, seed));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_RMatrixSampling_simple_swap_n", (DL_FUNC) &_RMatrixSampling_simple_swap_n, 5},
    {"_RMatrixSampling_swap_n", (DL_FUNC) &_RMatrixSampling_swap_n, 7},
    {NULL, NULL, 0}
};

RcppExport void R_init_RMatrixSampling(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
