# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' simple_swap_n
#'
#' Perform repeated checkerboard swaps in an adjacency matrix of a simple directed graph
#' This swapping produces a draws from the uniform distribution of all directed graphs
#' with the same row and column sums.
#'
#' @param Re_from list of originating vertices for each edge
#' @param Re_to list of terminating vertices for each edge
#' @param n number of swaps to perform
#' @param swap_p base probability of performing a swap (need swap_p < 1 for aperiodicity)
#' @param seed optional seed for random number generators
#' @export
simple_swap_n <- function(Re_from, Re_to, n, swap_p, seed = -1) {
    .Call('_RMatrixSampling_simple_swap_n', PACKAGE = 'RMatrixSampling', Re_from, Re_to, n, swap_p, seed)
}

#' swap_n
#'
#' Perform repeated checkerboard swaps in an adjacency matrix of a simple directed graph,
#' respecting structural zeros and swapping according to weights.
#' This swapping produces a draws from the non-uniform distribution of all directed graphs
#' with the same row and column sums, with probabilities determined by the edge weights.
#'
#' @param Re_from list of originating vertices for each edge
#' @param Re_to list of terminating vertices for each edge
#' @param n number of swaps to perform
#' @param Rz_from list of originating vertices for each structural zero
#' @param Rz_to list of terminating vertices for each structural zero
#' @param swap_p base probability of performing a swap (need swap_p < 1 for aperiodicity).
#' @param seed optional seed for random number generators
#' @export
swap_n <- function(Re_from, Re_to, n, Rw, Rz_from, Rz_to, seed = -1) {
    .Call('_RMatrixSampling_swap_n', PACKAGE = 'RMatrixSampling', Re_from, Re_to, n, Rw, Rz_from, Rz_to, seed)
}

